### ISSUE TITLE
Credentials for deploy?

### ISSUE THREAD

**Issue by addisonschultz** [butlerx/gatsby-source-google-spreadsheets#1]
Hey quick question. Great plugin, the only thing Im curious about is how you're going about adding the credentials `json` file included if I'm trying to deploy something through Netlify.

Should I pass each part of the JSON credentials as ENV variables?

Cheersxx

**Comment by butlerx** [comment]
currently, I pass the JSON as env  variables in netlify 
I have a function in my `gatsby-config.js` to parse the env variables and generate the JSON 
https://github.com/butlerx/invbeertory/blob/master/gatsby-config.js#L6

if you feel this is a better example or believe that the JSON example in the docs is poor pls feel free to update the docs

**Comment by addisonschultz** [comment]
Ah no that makes a lot of sense, I was just looking in the wrong place for this. Thank you a bunch!

**Comment by butlerx** [comment]
closing issue feel free to reopen or comment if you have more questiosn about deploying

**Comment by addisonschultz** [comment]
I did have one other question if you had encountered this while using the plugin. I see that images inserted into sheets return as null. I was reading https://stackoverflow.com/questions/39489282/retrieve-images-in-cells-using-google-sheets-api and it looks like it might be possible, but just wanted to see if you tried something like this and got it working

**Comment by butlerx** [comment]
I handt but if you open an issue i can have a look
