### ISSUE TITLE
Upgrade google spreadsheet dependency 

### ISSUE THREAD

**Issue by pjly458** [butlerx/gatsby-source-google-spreadsheets#4]
**Is your feature request related to a problem? Please describe.**
Error on building my site:
`WARNING! You must upgrade to the latest version of google-spreadsheet!
Google's deprecation date for the v3 sheets API is March 3rd 2020
Bad news - this version of this module will stop working on that date :(
Good news - the new version of the module uses the newer v4 api :)
However, there are breaking changes, so please see the docs site`

**Describe the solution you'd like**
Please could you update the version of google-spreadsheet in this module

**Comment by butlerx** [comment]
> Originally they were going to shut it down on March 3rd 2020, but have pushed that date back to September 30th.
 

so got a bit of time but will need to update

**Comment by butlerx** [comment]
This will break unauthenticated support so will need to be a major change.

**Comment by butlerx** [comment]
closed in v3.0.0. 
this Will cause a change to id if you where using them and you are now required to use a service account or api key for auth
